name: Build and Deploy to GitHub Pages

on:
    push:
        branches: ["main"] # Ensure this matches your default branch
    schedule:
        - cron: "0 0 * * *" # Adjust as needed

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Ruby
              uses: ruby/setup-ruby@v1
              with:
                  ruby-version: "3.3"

            - name: Install dependencies
              run: bundle install

            - name: Build site
              run: bundle exec jekyll build --future

            - name: Deploy to GitHub Pages
              uses: jeffreytse/jekyll-deploy-action@v0.6.0
              with:
                  provider: "github"
                  token: ${{ secrets.GH_PAT }} # Use the PAT
                  branch: "gh-pages"
