# This workflow deploys a Jekyll site to GitHub Pages
name: Deploy Jekyll site to GitHub Pages

on:
    push:
        branches:
            - master
    workflow_dispatch: # Allows manual execution from the Actions tab

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Ruby
              uses: ruby/setup-ruby@v1
              with:
                  ruby-version: "3.1"

            - name: Install dependencies and build Jekyll site
              run: |
                  bundle install
                  bundle exec jekyll build --baseurl ""

            - name: Archive artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: jekyll-site
                  path: _site # Assuming your Jekyll build output is in _site directory

    deploy:
        runs-on: ubuntu-latest
        needs: build

        steps:
            - name: Download artifacts
              uses: actions/download-artifact@v2
              with:
                  name: jekyll-site
                  path: _site # Specify the same path as uploaded

            - name: Deploy to GitHub Pages
              uses: actions/github-pages-deploy@v4
              with:
                  github_token: ${{ secrets.GH_PAT }} # Use a personal access token (GH_PAT) with repo scope
                  branch: gh-pages # Branch to deploy to
                  folder: _site # Folder to deploy

