name: Build and Deploy Jekyll site to GitHub Pages

on:
    push:
        branches:
            - master
    schedule:
        - cron: "0 0 * * *" # Runs at midnight every day

jobs:
    build-deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pages: write
            id-token: write
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup Pages
              uses: actions/configure-pages@v5

            - name: Build Jekyll site
              uses: actions/jekyll-build-pages@v1
              with:
                  destination: "./_site" # Specify your Jekyll build output directory
                  token: ${{ secrets.GH_PAT }} # Use your GH_PAT secret for authentication

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: "./_site" # Specify the path to your Jekyll build output

            - name: Deploy to GitHub Pages
              uses: actions/deploy-pages@v4
              with:
                  token: ${{ secrets.GH_PAT }} # Use your GH_PAT secret for authentication
