name: Build and Deploy Jekyll site to GitHub Pages

on:
    push:
        branches:
            - master

jobs:
    build-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup Pages
              uses: actions/configure-pages@v5

            - name: Build Jekyll site
              uses: actions/jekyll-build-pages@v1
              with:
                  destination: "./_site" # Specify your Jekyll build output directory
                  token: ${{ secrets.GH_PAT }} # Use your GH_PAT secret for authentication

            - name: Deploy to GitHub Pages
              uses: actions/deploy-pages@v4
              with:
                  token: ${{ secrets.GH_PAT }} # Use your GH_PAT secret for authentication
                  branch: gh-pages # Specify the branch to deploy to, often 'gh-pages'
